name: Run code review on PR

on:
  pull_request:
    types: [opened]

jobs:
  run-go-image:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull aolb/qreview:latest

      - name: Run the Docker container
        env:
          AI_CLIENT: ${{ secrets.AI_CLIENT }}
          FILE_EXTENSIONS: ${{ secrets.FILE_EXTENSIONS }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run:  |
          docker run \
            -e PR_URL="$PR_URL" \
            -e AI_CLIENT="$AI_CLIENT" \
            -e FILE_EXTENSIONS="$FILE_EXTENSIONS" \
            -e GITHUB_TOKEN="$GITHUB_TOKEN" \
            -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
            -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
            -e AWS_REGION="$AWS_REGION" \
            aolb/qreview